export const HOME_TOPMENU_INIT = 'HOME_TOPMENU_INIT';
export const HOME_TYPELIST_INIT = 'HOME_TYPELIST_INIT';
export const HOME_SHOW_LOADING = 'HOME_SHOW_LOADING';
export const HOME_BLOG_INIT = 'HOME_BLOG_INIT';
