export const HOME_TOPMENU_INIT = 'HOME_TOPMENU_INIT';
export const HOME_TYPELIST_INIT = 'HOME_TYPELIST_INIT';
export const HOME_BLOG_LIST_LOADING = 'HOME_BLOG_LIST_LOADING';
export const HOME_BLOG_LIST_SUCCESS = 'HOME_BLOG_LIST_SUCCESS';
export const HOME_BLOG_LIST_ERROR = 'HOME_BLOG_LIST_ERROR';
