export const HOME_TOPMENU_INIT = 'HOME_TOPMENU_INIT';
export const HOME_TYPELIST_INIT = 'HOME_TYPELIST_INIT';
//博客显示列表
export const HOME_BLOG_LIST_LOADING = 'HOME_BLOG_LIST_LOADING';
export const HOME_BLOG_LIST_SUCCESS = 'HOME_BLOG_LIST_SUCCESS';
export const HOME_BLOG_LIST_ERROR = 'HOME_BLOG_LIST_ERROR';
//博客新增页
export const HOME_BLOG_FORM_ADD_LOADING = 'HOME_BLOG_FORM_ADD_LOADING';
export const HOME_BLOG_FORM_ADD_SUCCESS = 'HOME_BLOG_FORM_ADD_SUCCESS';
export const HOME_BLOG_FORM_ADD_ERROR = 'HOME_BLOG_FORM_ADD_ERROR';
export const HOME_BLOG_FORM_INPUT_TITLE = 'HOME_BLOG_FORM_INPUT_TITLE';
export const HOME_BLOG_FORM_INPUT_CONTENT = 'HOME_BLOG_FORM_INPUT_CONTENT';
